export {ReactComponent as HomeIcon} from './icons/home-dashboard.svg'
export {ReactComponent as Logo} from './icons/logo.svg'
export {ReactComponent as BriefcaseIcon} from './icons/briefcase-icon.svg'
export {ReactComponent as BriefcaseIconFill} from './icons/icon-briefcasefill.svg'
export {ReactComponent as CompanyIcon} from './icons/company-dashboard.svg'
export {ReactComponent as AccountIcon} from './icons/account-dashboard.svg'
export {ReactComponent as NotificationIcon} from './icons/notification-icon.svg'
export {ReactComponent as EmailIcon} from './icons/email-icon.svg'
export {ReactComponent as SettingIcon} from './icons/settings-icon.svg'
// export {ReactComponent as Avatar} from './icons/avatar.png'